### ISSUE TITLE
Provide License

### ISSUE THREAD

**Issue by agarrharr** [rupa/j#1]
I couldn't find a license with this code. Could you add an open source license? I recommend MIT.

**Comment by rupa** [comment]
it would be WTFPL, but this is not a project intended for use. I should probably have deleted it long ago, but left it for code archaeologists. As noted in the readme, `z` is the one I'd encourage using.

**Comment by agarrharr** [comment]
Sounds good. I'll actually just remove it from my list since you recommend `z` instead.
